// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/config.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/config.go --destination mock/m_config_utils.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	core "github.com/torloejborg/easykube/pkg/core"
	gomock "go.uber.org/mock/gomock"
)

// MockIEasykubeConfig is a mock of IEasykubeConfig interface.
type MockIEasykubeConfig struct {
	ctrl     *gomock.Controller
	recorder *MockIEasykubeConfigMockRecorder
	isgomock struct{}
}

// MockIEasykubeConfigMockRecorder is the mock recorder for MockIEasykubeConfig.
type MockIEasykubeConfigMockRecorder struct {
	mock *MockIEasykubeConfig
}

// NewMockIEasykubeConfig creates a new mock instance.
func NewMockIEasykubeConfig(ctrl *gomock.Controller) *MockIEasykubeConfig {
	mock := &MockIEasykubeConfig{ctrl: ctrl}
	mock.recorder = &MockIEasykubeConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEasykubeConfig) EXPECT() *MockIEasykubeConfigMockRecorder {
	return m.recorder
}

// CopyConfigResources mocks base method.
func (m *MockIEasykubeConfig) CopyConfigResources() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyConfigResources")
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyConfigResources indicates an expected call of CopyConfigResources.
func (mr *MockIEasykubeConfigMockRecorder) CopyConfigResources() *MockIEasykubeConfigCopyConfigResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyConfigResources", reflect.TypeOf((*MockIEasykubeConfig)(nil).CopyConfigResources))
	return &MockIEasykubeConfigCopyConfigResourcesCall{Call: call}
}

// MockIEasykubeConfigCopyConfigResourcesCall wrap *gomock.Call
type MockIEasykubeConfigCopyConfigResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigCopyConfigResourcesCall) Return(arg0 error) *MockIEasykubeConfigCopyConfigResourcesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigCopyConfigResourcesCall) Do(f func() error) *MockIEasykubeConfigCopyConfigResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigCopyConfigResourcesCall) DoAndReturn(f func() error) *MockIEasykubeConfigCopyConfigResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EditConfig mocks base method.
func (m *MockIEasykubeConfig) EditConfig() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditConfig")
	ret0, _ := ret[0].(error)
	return ret0
}

// EditConfig indicates an expected call of EditConfig.
func (mr *MockIEasykubeConfigMockRecorder) EditConfig() *MockIEasykubeConfigEditConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditConfig", reflect.TypeOf((*MockIEasykubeConfig)(nil).EditConfig))
	return &MockIEasykubeConfigEditConfigCall{Call: call}
}

// MockIEasykubeConfigEditConfigCall wrap *gomock.Call
type MockIEasykubeConfigEditConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigEditConfigCall) Return(arg0 error) *MockIEasykubeConfigEditConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigEditConfigCall) Do(f func() error) *MockIEasykubeConfigEditConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigEditConfigCall) DoAndReturn(f func() error) *MockIEasykubeConfigEditConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GenerateZotRegistryConfig mocks base method.
func (m *MockIEasykubeConfig) GenerateZotRegistryConfig(arg0 *core.EasykubeConfigData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateZotRegistryConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateZotRegistryConfig indicates an expected call of GenerateZotRegistryConfig.
func (mr *MockIEasykubeConfigMockRecorder) GenerateZotRegistryConfig(arg0 any) *MockIEasykubeConfigGenerateZotRegistryConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateZotRegistryConfig", reflect.TypeOf((*MockIEasykubeConfig)(nil).GenerateZotRegistryConfig), arg0)
	return &MockIEasykubeConfigGenerateZotRegistryConfigCall{Call: call}
}

// MockIEasykubeConfigGenerateZotRegistryConfigCall wrap *gomock.Call
type MockIEasykubeConfigGenerateZotRegistryConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigGenerateZotRegistryConfigCall) Return(arg0 error) *MockIEasykubeConfigGenerateZotRegistryConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigGenerateZotRegistryConfigCall) Do(f func(*core.EasykubeConfigData) error) *MockIEasykubeConfigGenerateZotRegistryConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigGenerateZotRegistryConfigCall) DoAndReturn(f func(*core.EasykubeConfigData) error) *MockIEasykubeConfigGenerateZotRegistryConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GenerateZotRegistryCredentials mocks base method.
func (m *MockIEasykubeConfig) GenerateZotRegistryCredentials(arg0 *core.EasykubeConfigData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateZotRegistryCredentials", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateZotRegistryCredentials indicates an expected call of GenerateZotRegistryCredentials.
func (mr *MockIEasykubeConfigMockRecorder) GenerateZotRegistryCredentials(arg0 any) *MockIEasykubeConfigGenerateZotRegistryCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateZotRegistryCredentials", reflect.TypeOf((*MockIEasykubeConfig)(nil).GenerateZotRegistryCredentials), arg0)
	return &MockIEasykubeConfigGenerateZotRegistryCredentialsCall{Call: call}
}

// MockIEasykubeConfigGenerateZotRegistryCredentialsCall wrap *gomock.Call
type MockIEasykubeConfigGenerateZotRegistryCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigGenerateZotRegistryCredentialsCall) Return(arg0 error) *MockIEasykubeConfigGenerateZotRegistryCredentialsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigGenerateZotRegistryCredentialsCall) Do(f func(*core.EasykubeConfigData) error) *MockIEasykubeConfigGenerateZotRegistryCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigGenerateZotRegistryCredentialsCall) DoAndReturn(f func(*core.EasykubeConfigData) error) *MockIEasykubeConfigGenerateZotRegistryCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasConfiguration mocks base method.
func (m *MockIEasykubeConfig) HasConfiguration() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasConfiguration")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasConfiguration indicates an expected call of HasConfiguration.
func (mr *MockIEasykubeConfigMockRecorder) HasConfiguration() *MockIEasykubeConfigHasConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasConfiguration", reflect.TypeOf((*MockIEasykubeConfig)(nil).HasConfiguration))
	return &MockIEasykubeConfigHasConfigurationCall{Call: call}
}

// MockIEasykubeConfigHasConfigurationCall wrap *gomock.Call
type MockIEasykubeConfigHasConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigHasConfigurationCall) Return(arg0 bool) *MockIEasykubeConfigHasConfigurationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigHasConfigurationCall) Do(f func() bool) *MockIEasykubeConfigHasConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigHasConfigurationCall) DoAndReturn(f func() bool) *MockIEasykubeConfigHasConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsZotConfigInSync mocks base method.
func (m *MockIEasykubeConfig) IsZotConfigInSync(configData *core.EasykubeConfigData) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsZotConfigInSync", configData)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsZotConfigInSync indicates an expected call of IsZotConfigInSync.
func (mr *MockIEasykubeConfigMockRecorder) IsZotConfigInSync(configData any) *MockIEasykubeConfigIsZotConfigInSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsZotConfigInSync", reflect.TypeOf((*MockIEasykubeConfig)(nil).IsZotConfigInSync), configData)
	return &MockIEasykubeConfigIsZotConfigInSyncCall{Call: call}
}

// MockIEasykubeConfigIsZotConfigInSyncCall wrap *gomock.Call
type MockIEasykubeConfigIsZotConfigInSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigIsZotConfigInSyncCall) Return(arg0 bool, arg1 error) *MockIEasykubeConfigIsZotConfigInSyncCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigIsZotConfigInSyncCall) Do(f func(*core.EasykubeConfigData) (bool, error)) *MockIEasykubeConfigIsZotConfigInSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigIsZotConfigInSyncCall) DoAndReturn(f func(*core.EasykubeConfigData) (bool, error)) *MockIEasykubeConfigIsZotConfigInSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LaunchEditor mocks base method.
func (m *MockIEasykubeConfig) LaunchEditor(config, editor string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LaunchEditor", config, editor)
}

// LaunchEditor indicates an expected call of LaunchEditor.
func (mr *MockIEasykubeConfigMockRecorder) LaunchEditor(config, editor any) *MockIEasykubeConfigLaunchEditorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LaunchEditor", reflect.TypeOf((*MockIEasykubeConfig)(nil).LaunchEditor), config, editor)
	return &MockIEasykubeConfigLaunchEditorCall{Call: call}
}

// MockIEasykubeConfigLaunchEditorCall wrap *gomock.Call
type MockIEasykubeConfigLaunchEditorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigLaunchEditorCall) Return() *MockIEasykubeConfigLaunchEditorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigLaunchEditorCall) Do(f func(string, string)) *MockIEasykubeConfigLaunchEditorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigLaunchEditorCall) DoAndReturn(f func(string, string)) *MockIEasykubeConfigLaunchEditorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadConfig mocks base method.
func (m *MockIEasykubeConfig) LoadConfig() (*core.EasykubeConfigData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfig")
	ret0, _ := ret[0].(*core.EasykubeConfigData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfig indicates an expected call of LoadConfig.
func (mr *MockIEasykubeConfigMockRecorder) LoadConfig() *MockIEasykubeConfigLoadConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfig", reflect.TypeOf((*MockIEasykubeConfig)(nil).LoadConfig))
	return &MockIEasykubeConfigLoadConfigCall{Call: call}
}

// MockIEasykubeConfigLoadConfigCall wrap *gomock.Call
type MockIEasykubeConfigLoadConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigLoadConfigCall) Return(arg0 *core.EasykubeConfigData, arg1 error) *MockIEasykubeConfigLoadConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigLoadConfigCall) Do(f func() (*core.EasykubeConfigData, error)) *MockIEasykubeConfigLoadConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigLoadConfigCall) DoAndReturn(f func() (*core.EasykubeConfigData, error)) *MockIEasykubeConfigLoadConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MakeConfig mocks base method.
func (m *MockIEasykubeConfig) MakeConfig() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeConfig")
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeConfig indicates an expected call of MakeConfig.
func (mr *MockIEasykubeConfigMockRecorder) MakeConfig() *MockIEasykubeConfigMakeConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeConfig", reflect.TypeOf((*MockIEasykubeConfig)(nil).MakeConfig))
	return &MockIEasykubeConfigMakeConfigCall{Call: call}
}

// MockIEasykubeConfigMakeConfigCall wrap *gomock.Call
type MockIEasykubeConfigMakeConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigMakeConfigCall) Return(arg0 error) *MockIEasykubeConfigMakeConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigMakeConfigCall) Do(f func() error) *MockIEasykubeConfigMakeConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigMakeConfigCall) DoAndReturn(f func() error) *MockIEasykubeConfigMakeConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PathToConfigFile mocks base method.
func (m *MockIEasykubeConfig) PathToConfigFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathToConfigFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// PathToConfigFile indicates an expected call of PathToConfigFile.
func (mr *MockIEasykubeConfigMockRecorder) PathToConfigFile() *MockIEasykubeConfigPathToConfigFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathToConfigFile", reflect.TypeOf((*MockIEasykubeConfig)(nil).PathToConfigFile))
	return &MockIEasykubeConfigPathToConfigFileCall{Call: call}
}

// MockIEasykubeConfigPathToConfigFileCall wrap *gomock.Call
type MockIEasykubeConfigPathToConfigFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigPathToConfigFileCall) Return(arg0 string) *MockIEasykubeConfigPathToConfigFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigPathToConfigFileCall) Do(f func() string) *MockIEasykubeConfigPathToConfigFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigPathToConfigFileCall) DoAndReturn(f func() string) *MockIEasykubeConfigPathToConfigFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteConfig mocks base method.
func (m *MockIEasykubeConfig) WriteConfig(arg0 *core.EasykubeConfigData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteConfig indicates an expected call of WriteConfig.
func (mr *MockIEasykubeConfigMockRecorder) WriteConfig(arg0 any) *MockIEasykubeConfigWriteConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteConfig", reflect.TypeOf((*MockIEasykubeConfig)(nil).WriteConfig), arg0)
	return &MockIEasykubeConfigWriteConfigCall{Call: call}
}

// MockIEasykubeConfigWriteConfigCall wrap *gomock.Call
type MockIEasykubeConfigWriteConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIEasykubeConfigWriteConfigCall) Return(arg0 error) *MockIEasykubeConfigWriteConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIEasykubeConfigWriteConfigCall) Do(f func(*core.EasykubeConfigData) error) *MockIEasykubeConfigWriteConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIEasykubeConfigWriteConfigCall) DoAndReturn(f func(*core.EasykubeConfigData) error) *MockIEasykubeConfigWriteConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
