// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/ez/ek_singleton.go
//
// Generated by this command:
//
//	mockgen --source pkg/ez/ek_singleton.go --destination mocks/m_ek_singleton.go
//

// Package mock_ez is a generated GoMock package.
package mock_ez
