// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/osdetails.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/osdetails.go --destination mock/m_os_details.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOsDetails is a mock of IOsDetails interface.
type MockIOsDetails struct {
	ctrl     *gomock.Controller
	recorder *MockIOsDetailsMockRecorder
	isgomock struct{}
}

// MockIOsDetailsMockRecorder is the mock recorder for MockIOsDetails.
type MockIOsDetailsMockRecorder struct {
	mock *MockIOsDetails
}

// NewMockIOsDetails creates a new mock instance.
func NewMockIOsDetails(ctrl *gomock.Controller) *MockIOsDetails {
	mock := &MockIOsDetails{ctrl: ctrl}
	mock.recorder = &MockIOsDetailsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOsDetails) EXPECT() *MockIOsDetailsMockRecorder {
	return m.recorder
}

// GetEasykubeConfigDir mocks base method.
func (m *MockIOsDetails) GetEasykubeConfigDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEasykubeConfigDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEasykubeConfigDir indicates an expected call of GetEasykubeConfigDir.
func (mr *MockIOsDetailsMockRecorder) GetEasykubeConfigDir() *MockIOsDetailsGetEasykubeConfigDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEasykubeConfigDir", reflect.TypeOf((*MockIOsDetails)(nil).GetEasykubeConfigDir))
	return &MockIOsDetailsGetEasykubeConfigDirCall{Call: call}
}

// MockIOsDetailsGetEasykubeConfigDirCall wrap *gomock.Call
type MockIOsDetailsGetEasykubeConfigDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOsDetailsGetEasykubeConfigDirCall) Return(arg0 string, arg1 error) *MockIOsDetailsGetEasykubeConfigDirCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOsDetailsGetEasykubeConfigDirCall) Do(f func() (string, error)) *MockIOsDetailsGetEasykubeConfigDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOsDetailsGetEasykubeConfigDirCall) DoAndReturn(f func() (string, error)) *MockIOsDetailsGetEasykubeConfigDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserHomeDir mocks base method.
func (m *MockIOsDetails) GetUserHomeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHomeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHomeDir indicates an expected call of GetUserHomeDir.
func (mr *MockIOsDetailsMockRecorder) GetUserHomeDir() *MockIOsDetailsGetUserHomeDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHomeDir", reflect.TypeOf((*MockIOsDetails)(nil).GetUserHomeDir))
	return &MockIOsDetailsGetUserHomeDirCall{Call: call}
}

// MockIOsDetailsGetUserHomeDirCall wrap *gomock.Call
type MockIOsDetailsGetUserHomeDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOsDetailsGetUserHomeDirCall) Return(arg0 string, arg1 error) *MockIOsDetailsGetUserHomeDirCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOsDetailsGetUserHomeDirCall) Do(f func() (string, error)) *MockIOsDetailsGetUserHomeDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOsDetailsGetUserHomeDirCall) DoAndReturn(f func() (string, error)) *MockIOsDetailsGetUserHomeDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
