// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/printer.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/printer.go --destination mock/m_printer.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPrinter is a mock of IPrinter interface.
type MockIPrinter struct {
	ctrl     *gomock.Controller
	recorder *MockIPrinterMockRecorder
	isgomock struct{}
}

// MockIPrinterMockRecorder is the mock recorder for MockIPrinter.
type MockIPrinterMockRecorder struct {
	mock *MockIPrinter
}

// NewMockIPrinter creates a new mock instance.
func NewMockIPrinter(ctrl *gomock.Controller) *MockIPrinter {
	mock := &MockIPrinter{ctrl: ctrl}
	mock.recorder = &MockIPrinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPrinter) EXPECT() *MockIPrinterMockRecorder {
	return m.recorder
}

// FmtDryRun mocks base method.
func (m *MockIPrinter) FmtDryRun(out string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{out}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FmtDryRun", varargs...)
}

// FmtDryRun indicates an expected call of FmtDryRun.
func (mr *MockIPrinterMockRecorder) FmtDryRun(out any, args ...any) *MockIPrinterFmtDryRunCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{out}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FmtDryRun", reflect.TypeOf((*MockIPrinter)(nil).FmtDryRun), varargs...)
	return &MockIPrinterFmtDryRunCall{Call: call}
}

// MockIPrinterFmtDryRunCall wrap *gomock.Call
type MockIPrinterFmtDryRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPrinterFmtDryRunCall) Return() *MockIPrinterFmtDryRunCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPrinterFmtDryRunCall) Do(f func(string, ...any)) *MockIPrinterFmtDryRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPrinterFmtDryRunCall) DoAndReturn(f func(string, ...any)) *MockIPrinterFmtDryRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FmtGreen mocks base method.
func (m *MockIPrinter) FmtGreen(out string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{out}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FmtGreen", varargs...)
}

// FmtGreen indicates an expected call of FmtGreen.
func (mr *MockIPrinterMockRecorder) FmtGreen(out any, args ...any) *MockIPrinterFmtGreenCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{out}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FmtGreen", reflect.TypeOf((*MockIPrinter)(nil).FmtGreen), varargs...)
	return &MockIPrinterFmtGreenCall{Call: call}
}

// MockIPrinterFmtGreenCall wrap *gomock.Call
type MockIPrinterFmtGreenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPrinterFmtGreenCall) Return() *MockIPrinterFmtGreenCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPrinterFmtGreenCall) Do(f func(string, ...any)) *MockIPrinterFmtGreenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPrinterFmtGreenCall) DoAndReturn(f func(string, ...any)) *MockIPrinterFmtGreenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FmtRed mocks base method.
func (m *MockIPrinter) FmtRed(out string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{out}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FmtRed", varargs...)
}

// FmtRed indicates an expected call of FmtRed.
func (mr *MockIPrinterMockRecorder) FmtRed(out any, args ...any) *MockIPrinterFmtRedCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{out}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FmtRed", reflect.TypeOf((*MockIPrinter)(nil).FmtRed), varargs...)
	return &MockIPrinterFmtRedCall{Call: call}
}

// MockIPrinterFmtRedCall wrap *gomock.Call
type MockIPrinterFmtRedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPrinterFmtRedCall) Return() *MockIPrinterFmtRedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPrinterFmtRedCall) Do(f func(string, ...any)) *MockIPrinterFmtRedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPrinterFmtRedCall) DoAndReturn(f func(string, ...any)) *MockIPrinterFmtRedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FmtVerbose mocks base method.
func (m *MockIPrinter) FmtVerbose(out string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{out}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FmtVerbose", varargs...)
}

// FmtVerbose indicates an expected call of FmtVerbose.
func (mr *MockIPrinterMockRecorder) FmtVerbose(out any, args ...any) *MockIPrinterFmtVerboseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{out}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FmtVerbose", reflect.TypeOf((*MockIPrinter)(nil).FmtVerbose), varargs...)
	return &MockIPrinterFmtVerboseCall{Call: call}
}

// MockIPrinterFmtVerboseCall wrap *gomock.Call
type MockIPrinterFmtVerboseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPrinterFmtVerboseCall) Return() *MockIPrinterFmtVerboseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPrinterFmtVerboseCall) Do(f func(string, ...any)) *MockIPrinterFmtVerboseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPrinterFmtVerboseCall) DoAndReturn(f func(string, ...any)) *MockIPrinterFmtVerboseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FmtYellow mocks base method.
func (m *MockIPrinter) FmtYellow(out string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{out}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FmtYellow", varargs...)
}

// FmtYellow indicates an expected call of FmtYellow.
func (mr *MockIPrinterMockRecorder) FmtYellow(out any, args ...any) *MockIPrinterFmtYellowCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{out}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FmtYellow", reflect.TypeOf((*MockIPrinter)(nil).FmtYellow), varargs...)
	return &MockIPrinterFmtYellowCall{Call: call}
}

// MockIPrinterFmtYellowCall wrap *gomock.Call
type MockIPrinterFmtYellowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPrinterFmtYellowCall) Return() *MockIPrinterFmtYellowCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPrinterFmtYellowCall) Do(f func(string, ...any)) *MockIPrinterFmtYellowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPrinterFmtYellowCall) DoAndReturn(f func(string, ...any)) *MockIPrinterFmtYellowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
