// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/skaffold.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/skaffold.go --destination mock/m_skaffold.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISkaffold is a mock of ISkaffold interface.
type MockISkaffold struct {
	ctrl     *gomock.Controller
	recorder *MockISkaffoldMockRecorder
	isgomock struct{}
}

// MockISkaffoldMockRecorder is the mock recorder for MockISkaffold.
type MockISkaffoldMockRecorder struct {
	mock *MockISkaffold
}

// NewMockISkaffold creates a new mock instance.
func NewMockISkaffold(ctrl *gomock.Controller) *MockISkaffold {
	mock := &MockISkaffold{ctrl: ctrl}
	mock.recorder = &MockISkaffoldMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkaffold) EXPECT() *MockISkaffoldMockRecorder {
	return m.recorder
}

// CreateNewAddon mocks base method.
func (m *MockISkaffold) CreateNewAddon(name, dest string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateNewAddon", name, dest)
}

// CreateNewAddon indicates an expected call of CreateNewAddon.
func (mr *MockISkaffoldMockRecorder) CreateNewAddon(name, dest any) *MockISkaffoldCreateNewAddonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewAddon", reflect.TypeOf((*MockISkaffold)(nil).CreateNewAddon), name, dest)
	return &MockISkaffoldCreateNewAddonCall{Call: call}
}

// MockISkaffoldCreateNewAddonCall wrap *gomock.Call
type MockISkaffoldCreateNewAddonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISkaffoldCreateNewAddonCall) Return() *MockISkaffoldCreateNewAddonCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISkaffoldCreateNewAddonCall) Do(f func(string, string)) *MockISkaffoldCreateNewAddonCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISkaffoldCreateNewAddonCall) DoAndReturn(f func(string, string)) *MockISkaffoldCreateNewAddonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
