// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/status.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/status.go --destination mock/m_status.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIStatusBuilder is a mock of IStatusBuilder interface.
type MockIStatusBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockIStatusBuilderMockRecorder
	isgomock struct{}
}

// MockIStatusBuilderMockRecorder is the mock recorder for MockIStatusBuilder.
type MockIStatusBuilderMockRecorder struct {
	mock *MockIStatusBuilder
}

// NewMockIStatusBuilder creates a new mock instance.
func NewMockIStatusBuilder(ctrl *gomock.Controller) *MockIStatusBuilder {
	mock := &MockIStatusBuilder{ctrl: ctrl}
	mock.recorder = &MockIStatusBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStatusBuilder) EXPECT() *MockIStatusBuilderMockRecorder {
	return m.recorder
}

// DoAddonRepositoryCheck mocks base method.
func (m *MockIStatusBuilder) DoAddonRepositoryCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAddonRepositoryCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// DoAddonRepositoryCheck indicates an expected call of DoAddonRepositoryCheck.
func (mr *MockIStatusBuilderMockRecorder) DoAddonRepositoryCheck() *MockIStatusBuilderDoAddonRepositoryCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAddonRepositoryCheck", reflect.TypeOf((*MockIStatusBuilder)(nil).DoAddonRepositoryCheck))
	return &MockIStatusBuilderDoAddonRepositoryCheckCall{Call: call}
}

// MockIStatusBuilderDoAddonRepositoryCheckCall wrap *gomock.Call
type MockIStatusBuilderDoAddonRepositoryCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderDoAddonRepositoryCheckCall) Return(arg0 error) *MockIStatusBuilderDoAddonRepositoryCheckCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderDoAddonRepositoryCheckCall) Do(f func() error) *MockIStatusBuilderDoAddonRepositoryCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderDoAddonRepositoryCheckCall) DoAndReturn(f func() error) *MockIStatusBuilderDoAddonRepositoryCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DoBinaryCheck mocks base method.
func (m *MockIStatusBuilder) DoBinaryCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoBinaryCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// DoBinaryCheck indicates an expected call of DoBinaryCheck.
func (mr *MockIStatusBuilderMockRecorder) DoBinaryCheck() *MockIStatusBuilderDoBinaryCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoBinaryCheck", reflect.TypeOf((*MockIStatusBuilder)(nil).DoBinaryCheck))
	return &MockIStatusBuilderDoBinaryCheckCall{Call: call}
}

// MockIStatusBuilderDoBinaryCheckCall wrap *gomock.Call
type MockIStatusBuilderDoBinaryCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderDoBinaryCheckCall) Return(arg0 error) *MockIStatusBuilderDoBinaryCheckCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderDoBinaryCheckCall) Do(f func() error) *MockIStatusBuilderDoBinaryCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderDoBinaryCheckCall) DoAndReturn(f func() error) *MockIStatusBuilderDoBinaryCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DoContainerCheck mocks base method.
func (m *MockIStatusBuilder) DoContainerCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoContainerCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// DoContainerCheck indicates an expected call of DoContainerCheck.
func (mr *MockIStatusBuilderMockRecorder) DoContainerCheck() *MockIStatusBuilderDoContainerCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoContainerCheck", reflect.TypeOf((*MockIStatusBuilder)(nil).DoContainerCheck))
	return &MockIStatusBuilderDoContainerCheckCall{Call: call}
}

// MockIStatusBuilderDoContainerCheckCall wrap *gomock.Call
type MockIStatusBuilderDoContainerCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderDoContainerCheckCall) Return(arg0 error) *MockIStatusBuilderDoContainerCheckCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderDoContainerCheckCall) Do(f func() error) *MockIStatusBuilderDoContainerCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderDoContainerCheckCall) DoAndReturn(f func() error) *MockIStatusBuilderDoContainerCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDockerVersion mocks base method.
func (m *MockIStatusBuilder) GetDockerVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDockerVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDockerVersion indicates an expected call of GetDockerVersion.
func (mr *MockIStatusBuilderMockRecorder) GetDockerVersion() *MockIStatusBuilderGetDockerVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDockerVersion", reflect.TypeOf((*MockIStatusBuilder)(nil).GetDockerVersion))
	return &MockIStatusBuilderGetDockerVersionCall{Call: call}
}

// MockIStatusBuilderGetDockerVersionCall wrap *gomock.Call
type MockIStatusBuilderGetDockerVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderGetDockerVersionCall) Return(arg0 string) *MockIStatusBuilderGetDockerVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderGetDockerVersionCall) Do(f func() string) *MockIStatusBuilderGetDockerVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderGetDockerVersionCall) DoAndReturn(f func() string) *MockIStatusBuilderGetDockerVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHelmVersion mocks base method.
func (m *MockIStatusBuilder) GetHelmVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelmVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHelmVersion indicates an expected call of GetHelmVersion.
func (mr *MockIStatusBuilderMockRecorder) GetHelmVersion() *MockIStatusBuilderGetHelmVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelmVersion", reflect.TypeOf((*MockIStatusBuilder)(nil).GetHelmVersion))
	return &MockIStatusBuilderGetHelmVersionCall{Call: call}
}

// MockIStatusBuilderGetHelmVersionCall wrap *gomock.Call
type MockIStatusBuilderGetHelmVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderGetHelmVersionCall) Return(arg0 string) *MockIStatusBuilderGetHelmVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderGetHelmVersionCall) Do(f func() string) *MockIStatusBuilderGetHelmVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderGetHelmVersionCall) DoAndReturn(f func() string) *MockIStatusBuilderGetHelmVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetKubectlVersion mocks base method.
func (m *MockIStatusBuilder) GetKubectlVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubectlVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetKubectlVersion indicates an expected call of GetKubectlVersion.
func (mr *MockIStatusBuilderMockRecorder) GetKubectlVersion() *MockIStatusBuilderGetKubectlVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubectlVersion", reflect.TypeOf((*MockIStatusBuilder)(nil).GetKubectlVersion))
	return &MockIStatusBuilderGetKubectlVersionCall{Call: call}
}

// MockIStatusBuilderGetKubectlVersionCall wrap *gomock.Call
type MockIStatusBuilderGetKubectlVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderGetKubectlVersionCall) Return(arg0 string) *MockIStatusBuilderGetKubectlVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderGetKubectlVersionCall) Do(f func() string) *MockIStatusBuilderGetKubectlVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderGetKubectlVersionCall) DoAndReturn(f func() string) *MockIStatusBuilderGetKubectlVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetKustomizeVersion mocks base method.
func (m *MockIStatusBuilder) GetKustomizeVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKustomizeVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetKustomizeVersion indicates an expected call of GetKustomizeVersion.
func (mr *MockIStatusBuilderMockRecorder) GetKustomizeVersion() *MockIStatusBuilderGetKustomizeVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKustomizeVersion", reflect.TypeOf((*MockIStatusBuilder)(nil).GetKustomizeVersion))
	return &MockIStatusBuilderGetKustomizeVersionCall{Call: call}
}

// MockIStatusBuilderGetKustomizeVersionCall wrap *gomock.Call
type MockIStatusBuilderGetKustomizeVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderGetKustomizeVersionCall) Return(arg0 string) *MockIStatusBuilderGetKustomizeVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderGetKustomizeVersionCall) Do(f func() string) *MockIStatusBuilderGetKustomizeVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderGetKustomizeVersionCall) DoAndReturn(f func() string) *MockIStatusBuilderGetKustomizeVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPodmanVersion mocks base method.
func (m *MockIStatusBuilder) GetPodmanVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodmanVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPodmanVersion indicates an expected call of GetPodmanVersion.
func (mr *MockIStatusBuilderMockRecorder) GetPodmanVersion() *MockIStatusBuilderGetPodmanVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodmanVersion", reflect.TypeOf((*MockIStatusBuilder)(nil).GetPodmanVersion))
	return &MockIStatusBuilderGetPodmanVersionCall{Call: call}
}

// MockIStatusBuilderGetPodmanVersionCall wrap *gomock.Call
type MockIStatusBuilderGetPodmanVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderGetPodmanVersionCall) Return(arg0 string) *MockIStatusBuilderGetPodmanVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderGetPodmanVersionCall) Do(f func() string) *MockIStatusBuilderGetPodmanVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderGetPodmanVersionCall) DoAndReturn(f func() string) *MockIStatusBuilderGetPodmanVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVersionStr mocks base method.
func (m *MockIStatusBuilder) GetVersionStr(in, wants string, inErr error) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionStr", in, wants, inErr)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVersionStr indicates an expected call of GetVersionStr.
func (mr *MockIStatusBuilderMockRecorder) GetVersionStr(in, wants, inErr any) *MockIStatusBuilderGetVersionStrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionStr", reflect.TypeOf((*MockIStatusBuilder)(nil).GetVersionStr), in, wants, inErr)
	return &MockIStatusBuilderGetVersionStrCall{Call: call}
}

// MockIStatusBuilderGetVersionStrCall wrap *gomock.Call
type MockIStatusBuilderGetVersionStrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStatusBuilderGetVersionStrCall) Return(arg0 string) *MockIStatusBuilderGetVersionStrCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStatusBuilderGetVersionStrCall) Do(f func(string, string, error) string) *MockIStatusBuilderGetVersionStrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStatusBuilderGetVersionStrCall) DoAndReturn(f func(string, string, error) string) *MockIStatusBuilderGetVersionStrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
