// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/task_manager.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/task_manager.go --destination mock/m_task_manager.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOrderedTask is a mock of IOrderedTask interface.
type MockIOrderedTask struct {
	ctrl     *gomock.Controller
	recorder *MockIOrderedTaskMockRecorder
	isgomock struct{}
}

// MockIOrderedTaskMockRecorder is the mock recorder for MockIOrderedTask.
type MockIOrderedTaskMockRecorder struct {
	mock *MockIOrderedTask
}

// NewMockIOrderedTask creates a new mock instance.
func NewMockIOrderedTask(ctrl *gomock.Controller) *MockIOrderedTask {
	mock := &MockIOrderedTask{ctrl: ctrl}
	mock.recorder = &MockIOrderedTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrderedTask) EXPECT() *MockIOrderedTaskMockRecorder {
	return m.recorder
}

// GetDependencies mocks base method.
func (m *MockIOrderedTask) GetDependencies() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependencies")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDependencies indicates an expected call of GetDependencies.
func (mr *MockIOrderedTaskMockRecorder) GetDependencies() *MockIOrderedTaskGetDependenciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependencies", reflect.TypeOf((*MockIOrderedTask)(nil).GetDependencies))
	return &MockIOrderedTaskGetDependenciesCall{Call: call}
}

// MockIOrderedTaskGetDependenciesCall wrap *gomock.Call
type MockIOrderedTaskGetDependenciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOrderedTaskGetDependenciesCall) Return(arg0 []string) *MockIOrderedTaskGetDependenciesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOrderedTaskGetDependenciesCall) Do(f func() []string) *MockIOrderedTaskGetDependenciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOrderedTaskGetDependenciesCall) DoAndReturn(f func() []string) *MockIOrderedTaskGetDependenciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetName mocks base method.
func (m *MockIOrderedTask) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIOrderedTaskMockRecorder) GetName() *MockIOrderedTaskGetNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIOrderedTask)(nil).GetName))
	return &MockIOrderedTaskGetNameCall{Call: call}
}

// MockIOrderedTaskGetNameCall wrap *gomock.Call
type MockIOrderedTaskGetNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOrderedTaskGetNameCall) Return(arg0 string) *MockIOrderedTaskGetNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOrderedTaskGetNameCall) Do(f func() string) *MockIOrderedTaskGetNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOrderedTaskGetNameCall) DoAndReturn(f func() string) *MockIOrderedTaskGetNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
