// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/utils.go
//
// Generated by this command:
//
//	mockgen -typed --source pkg/core/utils.go --destination mock/m_utils.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUtils is a mock of IUtils interface.
type MockIUtils struct {
	ctrl     *gomock.Controller
	recorder *MockIUtilsMockRecorder
	isgomock struct{}
}

// MockIUtilsMockRecorder is the mock recorder for MockIUtils.
type MockIUtilsMockRecorder struct {
	mock *MockIUtils
}

// NewMockIUtils creates a new mock instance.
func NewMockIUtils(ctrl *gomock.Controller) *MockIUtils {
	mock := &MockIUtils{ctrl: ctrl}
	mock.recorder = &MockIUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUtils) EXPECT() *MockIUtilsMockRecorder {
	return m.recorder
}

// CopyResourceToConfigDir mocks base method.
func (m *MockIUtils) CopyResourceToConfigDir(src, dest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyResourceToConfigDir", src, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyResourceToConfigDir indicates an expected call of CopyResourceToConfigDir.
func (mr *MockIUtilsMockRecorder) CopyResourceToConfigDir(src, dest any) *MockIUtilsCopyResourceToConfigDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyResourceToConfigDir", reflect.TypeOf((*MockIUtils)(nil).CopyResourceToConfigDir), src, dest)
	return &MockIUtilsCopyResourceToConfigDirCall{Call: call}
}

// MockIUtilsCopyResourceToConfigDirCall wrap *gomock.Call
type MockIUtilsCopyResourceToConfigDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsCopyResourceToConfigDirCall) Return(arg0 error) *MockIUtilsCopyResourceToConfigDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsCopyResourceToConfigDirCall) Do(f func(string, string) error) *MockIUtilsCopyResourceToConfigDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsCopyResourceToConfigDirCall) DoAndReturn(f func(string, string) error) *MockIUtilsCopyResourceToConfigDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FileOrDirExists mocks base method.
func (m *MockIUtils) FileOrDirExists(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileOrDirExists", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FileOrDirExists indicates an expected call of FileOrDirExists.
func (mr *MockIUtilsMockRecorder) FileOrDirExists(path any) *MockIUtilsFileOrDirExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileOrDirExists", reflect.TypeOf((*MockIUtils)(nil).FileOrDirExists), path)
	return &MockIUtilsFileOrDirExistsCall{Call: call}
}

// MockIUtilsFileOrDirExistsCall wrap *gomock.Call
type MockIUtilsFileOrDirExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsFileOrDirExistsCall) Return(arg0 bool) *MockIUtilsFileOrDirExistsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsFileOrDirExistsCall) Do(f func(string) bool) *MockIUtilsFileOrDirExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsFileOrDirExistsCall) DoAndReturn(f func(string) bool) *MockIUtilsFileOrDirExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasBinary mocks base method.
func (m *MockIUtils) HasBinary(bin string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBinary", bin)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasBinary indicates an expected call of HasBinary.
func (mr *MockIUtilsMockRecorder) HasBinary(bin any) *MockIUtilsHasBinaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBinary", reflect.TypeOf((*MockIUtils)(nil).HasBinary), bin)
	return &MockIUtilsHasBinaryCall{Call: call}
}

// MockIUtilsHasBinaryCall wrap *gomock.Call
type MockIUtilsHasBinaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsHasBinaryCall) Return(arg0 bool) *MockIUtilsHasBinaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsHasBinaryCall) Do(f func(string) bool) *MockIUtilsHasBinaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsHasBinaryCall) DoAndReturn(f func(string) bool) *MockIUtilsHasBinaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IntSliceToStrings mocks base method.
func (m *MockIUtils) IntSliceToStrings(input []int) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntSliceToStrings", input)
	ret0, _ := ret[0].([]string)
	return ret0
}

// IntSliceToStrings indicates an expected call of IntSliceToStrings.
func (mr *MockIUtilsMockRecorder) IntSliceToStrings(input any) *MockIUtilsIntSliceToStringsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntSliceToStrings", reflect.TypeOf((*MockIUtils)(nil).IntSliceToStrings), input)
	return &MockIUtilsIntSliceToStringsCall{Call: call}
}

// MockIUtilsIntSliceToStringsCall wrap *gomock.Call
type MockIUtilsIntSliceToStringsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsIntSliceToStringsCall) Return(arg0 []string) *MockIUtilsIntSliceToStringsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsIntSliceToStringsCall) Do(f func([]int) []string) *MockIUtilsIntSliceToStringsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsIntSliceToStringsCall) DoAndReturn(f func([]int) []string) *MockIUtilsIntSliceToStringsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadFileToBytes mocks base method.
func (m *MockIUtils) ReadFileToBytes(filename string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileToBytes", filename)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileToBytes indicates an expected call of ReadFileToBytes.
func (mr *MockIUtilsMockRecorder) ReadFileToBytes(filename any) *MockIUtilsReadFileToBytesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileToBytes", reflect.TypeOf((*MockIUtils)(nil).ReadFileToBytes), filename)
	return &MockIUtilsReadFileToBytesCall{Call: call}
}

// MockIUtilsReadFileToBytesCall wrap *gomock.Call
type MockIUtilsReadFileToBytesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsReadFileToBytesCall) Return(arg0 []byte, arg1 error) *MockIUtilsReadFileToBytesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsReadFileToBytesCall) Do(f func(string) ([]byte, error)) *MockIUtilsReadFileToBytesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsReadFileToBytesCall) DoAndReturn(f func(string) ([]byte, error)) *MockIUtilsReadFileToBytesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadPropertyFile mocks base method.
func (m *MockIUtils) ReadPropertyFile(path string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPropertyFile", path)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPropertyFile indicates an expected call of ReadPropertyFile.
func (mr *MockIUtilsMockRecorder) ReadPropertyFile(path any) *MockIUtilsReadPropertyFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPropertyFile", reflect.TypeOf((*MockIUtils)(nil).ReadPropertyFile), path)
	return &MockIUtilsReadPropertyFileCall{Call: call}
}

// MockIUtilsReadPropertyFileCall wrap *gomock.Call
type MockIUtilsReadPropertyFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsReadPropertyFileCall) Return(arg0 map[string]string, arg1 error) *MockIUtilsReadPropertyFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsReadPropertyFileCall) Do(f func(string) (map[string]string, error)) *MockIUtilsReadPropertyFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsReadPropertyFileCall) DoAndReturn(f func(string) (map[string]string, error)) *MockIUtilsReadPropertyFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveFile mocks base method.
func (m *MockIUtils) SaveFile(data, dest string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveFile", data, dest)
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockIUtilsMockRecorder) SaveFile(data, dest any) *MockIUtilsSaveFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockIUtils)(nil).SaveFile), data, dest)
	return &MockIUtilsSaveFileCall{Call: call}
}

// MockIUtilsSaveFileCall wrap *gomock.Call
type MockIUtilsSaveFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsSaveFileCall) Return() *MockIUtilsSaveFileCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsSaveFileCall) Do(f func(string, string)) *MockIUtilsSaveFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsSaveFileCall) DoAndReturn(f func(string, string)) *MockIUtilsSaveFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveFileByte mocks base method.
func (m *MockIUtils) SaveFileByte(data []byte, dest string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveFileByte", data, dest)
}

// SaveFileByte indicates an expected call of SaveFileByte.
func (mr *MockIUtilsMockRecorder) SaveFileByte(data, dest any) *MockIUtilsSaveFileByteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileByte", reflect.TypeOf((*MockIUtils)(nil).SaveFileByte), data, dest)
	return &MockIUtilsSaveFileByteCall{Call: call}
}

// MockIUtilsSaveFileByteCall wrap *gomock.Call
type MockIUtilsSaveFileByteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIUtilsSaveFileByteCall) Return() *MockIUtilsSaveFileByteCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIUtilsSaveFileByteCall) Do(f func([]byte, string)) *MockIUtilsSaveFileByteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIUtilsSaveFileByteCall) DoAndReturn(f func([]byte, string)) *MockIUtilsSaveFileByteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
