site:
  title: EasyKube Documentation
  url: https://torloejborg.github.io/easykube
  start_page: easykube::index.adoc

urls:
  html_extension_style: default  # keep .html
  redirect_facility: disabled    # disable redirects for now

content:
  sources:
    - url: https://github.com/torloejborg/easykube
      branches: refac/improvements
      start_path: asciidoc
    - url: https://github.com/torloejborg/easykube/pkg/resources
      branches: refac/improvements
      start_path: data

output:
  dir: ./docs

runtime:
  fetch: true

asciidoc:
  attributes:
    toc: left
    toclevels: 3
    sectanchors: ''
    sectnums: ''

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    # disable the component and version selectors
    - path: partials/header-content.hbs
      contents: |
        {{!-- custom header with no component/version dropdowns --}}
        <header class="navbar">
          <div class="navbar-brand">
            <a class="navbar-item" href="{{@root.page.url}}">
              {{@root.site.title}}
            </a>
          </div>
        </header>