= Container Runtimes

Currently easykube support docker and podman container runtimes, each have subtle differences and modes of operation.

Chosing a runtime is done in the easykube configuration file

`$ easykube config`

== Docker

Docker is widely used, and can be found on many platforms combined with the desktop manager. In most cases docker runs with a set of permissive privileges (on default installations) it runs as the superuser (root) - which has it's pros and cons.

On a developer machine, elevated permissions are in many cases acceptable. However, in some organizations docker is banned because of security concerns.

Easykube has not been tested with rootless docker, for rootless operation consider using podman instead.

Privileged Docker mostly give less friction.

== Podman

In constrained environments, it's possible to use easykube together with rootless podman. If you are new to Podman, there are some subtle differences you should be aware of.

 Image names are not automatically resolved.

This means you must specify the fully qualified registry name for an image,
for instance;  the image `busybox:latest` won't automatically resolve with the podman go library. Using docker it's just assumed that the image lives on dockerhub, using Podman the image should be specified as `dockerhub.io/library/busybox:latest`.


[NOTE]
====
Easykube expects to talk to podman via a socket, on Linux systems this socket can typically be found in `/run/user/<uid>/podman/podman.socket`

If the socket it not there, and you are using a systemd based OS, try and start it with

`systemctl --user start podman.socket`

====
