= Extending
:icons: font

== The script runtime [[internals-js]]

Why scripting?

Easykube is meant to be flexible, and used in different contexts with different addon repositories. Easykube defines a core set of utility functions which can be combined in interesting ways via scripting.

Instead of inventing a dedicated _easykube-script_ language (which could be a fun challenge), it was instead decided to spare the innocent and use an existing library, enter https://github.com/dop251/goja[Goja], a Javascript VM for Golang.

Adding new core functionality is relatively straightforward. Below is the listing of the go file where all exported functions is declared.

[source,go]
.pkg/js/easykube.go
----
include::example$easykube.go[tag=export]
----

The *_ek* object is populated with a name and a function. To add a function, simply copy/paste an existing file and adapt.

Below the *env* function is listed
----
include::example$ek_env.go[tag=envfunc]
----

In a nutshell, define a function which has a pointer-receiver to Easykube that returns a function which returns a goja.Value.

