= Easykube documentation site

Easykube started out as a collection of Gradle build scripts. The primary use case was to enable mobile developers to install real backends locally, allowing them to work offline and not require a personal instance of some test system on a random cluster, incurring a real monetary cost.


Later, easykube was reimplemented in Go. And currently enables teams of developers to reason about complex microservice based applications, encouraging local experimentation.

If you want to know why easykube exists and what it’s all about, read the xref:about/rationale.adoc#rationale-rationale[rationale] page.

Next, visit the xref:gettingstarted/install.adoc[installation] page.

Also, you should familiarize yourself with the concepts of xref:addons.adoc[addons].

== Icons and their meaning
icon:terminal[role="big"] run this command in a terminal

icon:arrow-right[role="big"] move forward to a relevant topic

icon:arrow-left[role="big"] back to the previous topic

icon:eye[] A reference to a Javascript API function
