= Install, Configure, and Create[[install]]
:icons: font

Welcome! On these pages you will find guides on how to install, operate, and extend Easykube software to suit your own use cases.

== Installation[[install-install]]
There are many ways to install Easykube; below are some of the paths you can choose.

Please note that pre-built easykube binaries exist for Windows, Linux, and macOS. It will run on Windows, but it is recommended to run easykube in WSL2. On never macs you will need to explicitly allow the binary to run, I simply can't be arsed to communicate with Apple about signing and approval procedures, if you are trapped in that pit - build from source.

=== Nix [[install-nix]]
You can use https://nixos.org/download/#download-nix[nix] to speed up the process.

`nix develop github:/torloejborg/easykube`

This will fetch and build from source and automatically pull in the required binary dependencies (except Docker). You will then be dropped into a shell with all tooling available and can start using easykube.

[TIP]
.nix (~/.config/nix/nix.conf)
====
You may have to add the following to your nix.conf in order to silence Nix warnings:

----
extra-experimental-features = nix-command
extra-experimental-features = flakes
----

The Nix flake has two shells. The default will build easykube from source.

`nix develop .#light` will drop you into a shell with supporting tools *without building*. Useful if you cloned the repository.
====

=== Manual installation[[install-manual]]

Download the latest easykube binary for your platform https://github.com/torloejborg/easykube/releases[here].
Extract the archive, rename the binary to `easykube`, `ek`, or whatever you prefer, and make sure it is on your system’s PATH.

Use a package manager or download the following software yourself:

* https://www.docker.com/[docker]
* https://kubernetes.io/docs/tasks/tools/[kubectl]
* https://kubectl.docs.kubernetes.io/installation/kustomize/[kustomize]
* https://helm.sh/docs/intro/quickstart/#install-helm[helm]
* https://k9scli.io/topics/install/[k9s] (optional)

CAUTION: On some Linux systems, installing the above packages via snap has proved troublesome for easykube. It may work for you; it may not.

=== Post-installation check [[install-postcheck]]
Typing `easykube` in your shell should show a warning and usage description.

[source,text]
----
⚠ expecting /home/jane/.kube/easykube to exist, create the cluster and this message will disappear

bootstrap a single node kubernetes cluster, install development platforms via addon-repositories

hint: start with 'easykube config'
...
----

Also try `easykube status`; this should yield additional warnings and errors.

[source,text]
----
⚠ expecting /home/jane/.kube/easykube to exist, create the cluster and this message will disappear
Inspecting binary dependencies
✓ kubectl 1.34.1 (~1.34)
✓ docker 28.4.0 (^28)
✓ helm 3.19.0 (~3.19)
✓ kustomize 5.7.1 (~5.7)
...
----

The checks for the dependent binaries pass. Next, proceed to configuration.

== Configuration [[install-configuration]]
By itself, easykube is not very interesting—it cannot do anything without its companion addons, which you will find https://github.com/torloejborg/easykube-addons[here]. Clone (or download) the repository to your local machine.

NOTE: The next sections assume the addon repository is placed in `/home/jane/code/easykube-addons` — adjust accordingly.
