= Rationale [[rationale-rationale]]

* Easykube aims to enable sharing and distribution of development "platforms" via its companion addon repositories.

* It is meant as a team and individual enabler: everyone can install and work with an application’s particular stack locally, without breaking a shared environment.

* This is certainly doable with existing tooling—Docker Compose and friends are popular choices. So what’s the point of another tool?

* Kubernetes is also an orchestration platform.

* If you use Kubernetes for your workloads, why not re-use the deployments that already exist?

== Easykube [[rationale-easykube]]

* Easykube is built on top of the Kind project (Kubernetes in Docker) and the Goja JavaScript runtime Go library.

* It bootstraps a single-node Kind cluster with some small modifications.

* It automatically sets up a local Docker registry for the cluster and connects it, allowing air-gapped environments.

* Based on discovered addons, a Kind cluster configuration is generated for the particular addon repository’s use case (host ports and extra mounts).

* Persistent data (if used) survives cluster deletion.

* Addon dependency resolution.

* Addon installation is programmable via the embedded JavaScript runtime, making it highly customizable.

* A CoreDNS hack lets you access everything from "localtest.me" — never edit your /etc/hosts file again!

== What you can do with it [[rationale-dowith]]

* Enable your team to install and run your cloud-native application(s) locally—especially powerful when combined with tools like mirrord.

* Break things; it’s OK. Just start over.

* Effortlessly spin up a local development stack: databases, web servers, caches, workflow engines, OAuth servers, S3-compatible storage, etc.

* Use as a learning or teaching tool for Kubernetes.

* Perhaps some team members simply don’t care about Kubernetes—That’s OK, nobody can be forced to fall in love with YAML. Instead, `$ easykube add mystack` will have stuff running with minimal effort.

== Please do not [[rationale-donot]]

Use in a production setting. Run your real workloads on a secured cluster. Easykube is not built with security in mind, only for local workloads.
