= Adding New Stuff
:icons: font

== The Script Runtime [[internals-js]]

Adding new core functionality is relatively straightforward.
Below is the listing of the Go file where all exported functions are declared.

[source,go]
.pkg/js/easykube.go
----
include::example$easykube.go[tag=export]
----

The *_ek* object is populated with a name and a function.
To add a function, simply copy/paste an existing file and adapt it.

Below is the *env* function:

----
include::example$ek_env.go[tag=envfunc]
----

In a nutshell:
Define a method with a pointer receiver to `Easykube` that returns a function, which in turn returns a `goja.Value`.

== Mocks

`gomock` from Uber is used to generate mocks for most interfaces.
If an interface is changed, remember to regenerate the mocks.

Run:

`make mock`

== Keeping up-to-date

If you forked the repository, bought into the Nix philosophy, and think things
should be stable and reproducible. Just remember, after each new depencney added you should run `make gomod2nix`. This will sync go-packages to a known, reproducible state.
