package jsutils

const AddonDir = "addonDir"
const AndThenApply = "thenApply"
const Config = "config"
const CopyTo = "copyTo"
const CreateSecret = "createSecret"
const DockerExec = "dockerExec"
const Exec = "exec"
const ExecInContainer = "execInContainer"
const GetSecret = "getSecret"
const GitCheckout = "checkout"
const GitSparseCheckout = "sparseCheckout"
const HelmTemplate = "helmTemplate"
const Http = "http"
const KeyEnv = "env"
const KeyValue = "keyValue"
const Kustomize = "kustomize"
const Preload = "preload"
const ProcessSecrets = "processExternalSecrets"
const RestartDeployment = "restartDeployment"
const SkopeoPreload = "skopeoPreload"
const WaitForCrd = "waitForCRD"
const WaitForDeployment = "waitForDeployment"
