package jsutils

const AndThenApply = "thenApply"
const CopyTo = "copyTo"
const KeyValue = "keyValue"
const KeyEnv = "env"
const CreateSecret = "createSecret"
const ExecInContainer = "execInContainer"
const GetSecret = "getSecret"
const Preload = "preload"
const Kustomize = "kustomize"
const WaitForDeployment = "waitForDeployment"
const WaitForCrd = "waitForCRD"
const GitSparseCheckout = "sparseCheckout"
const GitCheckout = "checkout"
const HelmTemplate = "helmTemplate"
const ProcessSecrets = "processExternalSecrets"
const Http = "http"
const Exec = "exec"
const DockerExec = "dockerExec"
const AddonDir = "addonDir"
const Config = "config"
const RestartDeployment = "restartDeployment"
